# 程序名称
app.name=Tech-To-OceanBase
fs.defaultFS=hdfs://gkzacluster
#dfs.namenode.secondary.http-address=hadoop6:9868
#dfs.namenode.http-address=hadoop10:9870

# 手动 HA 配置（全部以 spark.hadoop. 为前缀）

dfs.nameservices=gkzacluster
dfs.ha.namenodes.gkzacluster=nn1,nn2
dfs.namenode.rpc-address.gkzacluster.nn1=hadoop10:8020
dfs.namenode.rpc-address.gkzacluster.nn2=hadoop15:8020
dfs.client.failover.proxy.provider.gkzacluster=org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

master=local[3]
# hive
hive.metastore.uris=thrift://hadoop6:9083
hive.default.database=database_01

# 分区数量
spark.sql.shuffle.partitions=1200

# 每次请求的数量
http.count=10000

# 告警地址
weChat=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ea529f1d-f509-4af5-a83e-76d9d642d6bf

weChat1=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=089efa4a-d6e7-45c1-af59-aa4265542189

# image 地址
image.domain=http://img.sticloud.cn/

image.tab=true

# druid地址
druid.name=mysql
druid.url=jdbc:mysql://172.16.8.120:2881/data_literature?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true&useSSL=false
druid.username=root@mysql_gkza
druid.password=123@qwe
druid.testWhileIdle=true
druid.testOnBorrow=false
druid.validationQuery=SELECT 1
druid.useGlobalDataSourceStat=false
druid.timeBetweenEvictionRunsMillis=60000
druid.initialSize=2
druid.minIdle=2
druid.maxActive=20

insert.ip=172.16.8.120
inset.table.port=2881


# mysql地址
mysqlUrl=jdbc:mysql://172.16.8.120:2881/data_literature?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true&useSSL=false
mysqlUser=root@mysql_gkza
mysqlPsd=123@qwe
mysqlTableName=attachment_manage_dev


# Flink
flink.parallelism=4
taskmanager.memory.network.min=1024mb
taskmanager.memory.network.max=1024mb
taskmanager.memory.network.fraction=0.2


local.file=hdfs://hadoop10:8020/tmp/local/zdhyb202503023.md

# Flink 读取 HDFS 文件路径（HA 集群 nameservice）
hdfs.read.path=hdfs://gkzacluster/special-database-json/2026-08-21/FlumeData.1787241953684.log
